nginx:
  build: nginx:latest
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "80:80"
php:
  build: php:7.3.13-fpm
  volumes:
    - ./images/php:/var/www/html
  working_dir: /var/www/html/app/public
  command: php-fpm
  links:
    - cache
  ports:
    - "9000:9000"
  environment:
    APP_ENV: local
    APP_DEBUG: 'false'
    APP_KEY: MyRandomKey!!!
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
    FA_LOGIN: https://app.formassembly.com
    FA_USERNAME: fa-assignment
    FA_PASSWORD: lVrC09TdJPhXpZPn8dc3
    FA_OAUTH_CLIENT_ID: U0SQO6NXhnQQIbdENjza
    FA_OAUTH_CLIENT_SECRET: xCQhmQ3vex4lznU9Ozss
cache:
  image: memcached
